"use client";

import { FormEvent, useMemo, useState } from "react";

type ModuleId = "bazi" | "marriage" | "daily" | "ziwei" | "ziweiMarriage" | "meihua" | "liuyao" | "tarot" | "huangli";
type Line = { yang: boolean; moving: boolean };
const stems = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"];
const branches = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"];
const elements = ["木", "火", "土", "金", "水"];
const trigramNames = ["坤", "震", "坎", "兑", "艮", "离", "巽", "乾"];
const trigramSymbols = ["☷", "☳", "☵", "☱", "☶", "☲", "☴", "☰"];
const moduleMeta: Record<ModuleId, { group: string; title: string; subtitle: string; icon: string }> = {
  bazi:{group:"八字命理",title:"八字排盘",subtitle:"四柱、五行与人生结构",icon:"八"}, marriage:{group:"八字命理",title:"八字合婚",subtitle:"关系优势与磨合提示",icon:"合"}, daily:{group:"八字命理",title:"每日运势",subtitle:"今天的节奏与行动建议",icon:"日"},
  ziwei:{group:"紫微斗数",title:"紫微排盘",subtitle:"十二宫位与核心星曜",icon:"紫"}, ziweiMarriage:{group:"紫微斗数",title:"紫微合盘",subtitle:"双人宫位互动观察",icon:"缘"},
  meihua:{group:"周易占问",title:"梅花易数",subtitle:"时间与数字的快速决策卦",icon:"梅"}, liuyao:{group:"周易占问",title:"六爻占卜",subtitle:"本卦、变卦与动爻分析",icon:"爻"},
  tarot:{group:"灵感探索",title:"塔罗牌阵",subtitle:"三张牌梳理过去、当下与建议",icon:"牌"}, huangli:{group:"生活择时",title:"AI 老黄历",subtitle:"每日宜忌、吉时与节奏",icon:"历"},
};
const navGroups: [string, ModuleId[]][] = [["八字命理",["bazi","marriage","daily"]],["紫微斗数",["ziwei","ziweiMarriage"]],["周易占问",["meihua","liuyao"]],["灵感与择时",["tarot","huangli"]]];

function hash(text: string) { let h=2166136261; for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)} return Math.abs(h); }
function seeded(seed:number,index:number,max:number){return Math.abs(Math.floor(Math.sin(seed*(index+1)*12.9898)*43758.5453))%max}
function pillars(date:string,time="12:00") { const d=new Date(`${date}T${time||"12:00"}`); const seed=Math.floor(d.getTime()/86400000); return [0,1,2,3].map(i=>stems[seeded(seed,i,10)]+branches[seeded(seed,i+4,12)]); }
function fiveElements(seed:number){const vals=elements.map((_,i)=>28+seeded(seed,i,65));const total=vals.reduce((a,b)=>a+b,0);return vals.map(v=>Math.round(v/total*100));}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="tool-field"><span>{label}</span>{children}</label>}
function Submit({children="生成分析"}:{children?:React.ReactNode}){return <button className="tool-submit">{children}<span>→</span></button>}
function ModuleHead({id}:{id:ModuleId}){const m=moduleMeta[id];return <div className="module-hero"><div><p className="eyebrow">{m.group} · 本地隐私计算</p><h2>{m.title}</h2><p>{m.subtitle}。输入只在当前设备处理，不会上传。</p></div><div className="module-seal">{m.icon}</div></div>}

export default function Home(){
  const [active,setActive]=useState<ModuleId>("bazi"); const [mobile,setMobile]=useState(false); const meta=moduleMeta[active];
  return <main className="workspace-shell">
    <aside className={`sidebar ${mobile?"open":""}`}><button className="brand brand-button" onClick={()=>setActive("bazi")}><span>知</span><div>知命<small>东方智慧工作台</small></div></button><nav>{navGroups.map(([group,ids])=><section key={group}><p>{group}</p>{ids.map(id=><button key={id} className={active===id?"active":""} onClick={()=>{setActive(id);setMobile(false);window.scrollTo({top:0,behavior:"smooth"})}}><i>{moduleMeta[id].icon}</i>{moduleMeta[id].title}<small>进入</small></button>)}</section>)}</nav><div className="side-foot"><div className="privacy-badge">● 本地隐私模式</div><p>所有计算在此设备完成</p></div></aside>
    <section className="workspace"><header id="top"><button className="menu" onClick={()=>setMobile(!mobile)}>☰</button><div><p>{meta.group} / {meta.title}</p><h1>知命 · 全域命理工作台</h1></div><div className="header-actions"><span>9 项工具可用</span><button onClick={()=>window.print()}>保存当前结果</button></div></header>
      <ModuleHead id={active}/><div className="module-stage">{active==="bazi"&&<Bazi/>}{active==="marriage"&&<Marriage kind="八字"/>}{active==="daily"&&<Daily/>}{active==="ziwei"&&<Ziwei/>}{active==="ziweiMarriage"&&<Marriage kind="紫微"/>}{active==="meihua"&&<Meihua/>}{active==="liuyao"&&<Liuyao/>}{active==="tarot"&&<Tarot/>}{active==="huangli"&&<Huangli/>}</div>
      <section className="trust-strip"><div><b>确定性排盘</b><span>相同输入得到相同基础盘</span></div><div><b>本地隐私</b><span>不要求注册，不上传出生信息</span></div><div><b>清晰边界</b><span>传统文化与娱乐参考，不替代专业判断</span></div></section>
      <footer><button className="brand brand-button" onClick={()=>setActive("bazi")}><span>知</span><div>知命<small>东方智慧工作台</small></div></button><p>不预言答案，只照亮选择。</p><small>© 2026 · 仅供传统文化研究与娱乐参考</small></footer>
    </section>
  </main>
}

function Bazi(){const [result,setResult]=useState<null|{name:string;ps:string[];five:number[];seed:number}>(null);function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const date=String(f.get("date")),time=String(f.get("time"));const seed=hash(date+time+f.get("name"));setResult({name:String(f.get("name")),ps:pillars(date,time),five:fiveElements(seed),seed});}return <><form className="tool-card" onSubmit={go}><div className="tool-title"><b>建立命盘</b><span>请输入公历出生信息</span></div><div className="form-grid"><Field label="称呼"><input name="name" required placeholder="例如：小知"/></Field><Field label="性别"><select name="gender"><option>女性</option><option>男性</option><option>不透露</option></select></Field><Field label="出生日期"><input name="date" required type="date" defaultValue="1995-06-18"/></Field><Field label="出生时间"><input name="time" required type="time" defaultValue="08:30"/></Field><Field label="出生城市"><input name="city" required placeholder="例如：杭州"/></Field><Field label="历法"><select><option>公历</option><option>农历（自动换算）</option></select></Field></div><Submit>开始八字排盘</Submit></form>{result&&<section className="tool-result"><ResultTitle kicker={`${result.name}的命盘`} title="四柱八字" note="年柱 · 月柱 · 日柱 · 时柱"/><div className="pillars">{result.ps.map((p,i)=><div key={p+i}><small>{["年柱","月柱","日柱","时柱"][i]}</small><strong>{p[0]}</strong><b>{p[1]}</b><span>{elements[seeded(result.seed,i,5)]}</span></div>)}</div><ElementBars values={result.five}/><InsightCards items={[["命局底色","你的结构偏向稳中求进，适合把复杂目标拆成持续积累的小步骤。"],["事业方向","先建立可重复的方法和作品，再追求规模；专业信誉会成为长期优势。"],["关系提示","表达真实需求比猜测更有效，清晰边界能够保护亲密感。"]]}/></section>}</>}

function Marriage({kind}:{kind:"八字"|"紫微"}){const [score,setScore]=useState<number|null>(null);function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setScore(58+hash([...f.values()].join(""))%38)}return <><form className="tool-card" onSubmit={go}><div className="dual-title"><div><b>甲方信息</b><span>关系中的自己</span></div><i>合</i><div><b>乙方信息</b><span>关系中的对方</span></div></div><div className="couple-grid"><div><Field label="甲方称呼"><input name="aName" required placeholder="称呼"/></Field><Field label="甲方出生日期"><input name="aDate" required type="date" defaultValue="1994-03-15"/></Field><Field label="甲方出生时间"><input name="aTime" type="time" defaultValue="10:00"/></Field></div><div><Field label="乙方称呼"><input name="bName" required placeholder="称呼"/></Field><Field label="乙方出生日期"><input name="bDate" required type="date" defaultValue="1996-09-08"/></Field><Field label="乙方出生时间"><input name="bTime" type="time" defaultValue="18:00"/></Field></div></div><Submit>生成{kind}合盘</Submit></form>{score!==null&&<section className="tool-result marriage-result"><div className="score-ring"><strong>{score}</strong><span>综合契合度</span></div><div><ResultTitle kicker={`${kind}关系观察`} title={score>82?"默契深厚，彼此成就":score>70?"优势互补，需要沟通":"差异明显，边界优先"} note="分数用于呈现互动维度，不代表关系结论"/><div className="dimension-bars">{[["沟通节奏",score-3],["情绪支持",Math.min(96,score+7)],["生活协作",score-8],["长期成长",Math.min(98,score+3)]].map(x=><label key={String(x[0])}><span>{x[0]}</span><i><b style={{width:`${x[1]}%`}}/></i><em>{x[1]}</em></label>)}</div></div><InsightCards items={[["共同优势","你们容易在目标明确时形成合力，适合一起完成可见的小项目。"],["磨合主题","压力之下的表达节奏不同，先确认情绪，再讨论解决方案。"],["相处建议","固定安排不被打扰的沟通时间，把期待说成具体可执行的请求。"]]}/></section>}</>}

function Daily(){const [data,setData]=useState<{score:number;date:string}|null>(null);function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const date=String(f.get("date"));setData({date,score:62+hash(date+f.get("birth"))%34})}return <><form className="tool-card inline-form" onSubmit={go}><Field label="出生日期"><input name="birth" required type="date" defaultValue="1995-06-18"/></Field><Field label="查看日期"><input name="date" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><Submit>查看当日运势</Submit></form>{data&&<section className="tool-result"><ResultTitle kicker={new Date(data.date).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"})} title={`今日能量 ${data.score} 分`} note="先做重要但不紧急的事"/><div className="fortune-grid">{[["事业","适合整理计划、推进已有合作","文档 / 深绿色"],["关系","少一些试探，多一些直白确认","散步 / 暖金色"],["财务","宜复盘订阅与固定支出","数字 6 / 西北方"],["身心","减少信息摄入，留出安静间隙","清茶 / 早睡"]].map((x,i)=><article key={String(x[0])}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p><span>{x[2]}</span></article>)}</div><div className="day-timeline"><b>07:00</b><span>整理与规划</span><b>11:00</b><span>沟通与推进</span><b>16:00</b><span>谨慎决策</span><b>21:00</b><span>复盘与休息</span></div></section>}</>}

function Ziwei(){const [seed,setSeed]=useState<number|null>(null);function go(e:FormEvent<HTMLFormElement>){e.preventDefault();setSeed(hash([...new FormData(e.currentTarget).values()].join("")))}const palaces=["命宫","兄弟","夫妻","子女","财帛","疾厄","迁移","交友","官禄","田宅","福德","父母"],stars=["紫微","天机","太阳","武曲","天同","廉贞","天府","太阴","贪狼","巨门","天相","天梁","七杀","破军"];return <><form className="tool-card inline-form" onSubmit={go}><Field label="出生日期"><input name="date" required type="date" defaultValue="1995-06-18"/></Field><Field label="出生时间"><input name="time" required type="time" defaultValue="08:30"/></Field><Field label="性别"><select name="gender"><option>女</option><option>男</option></select></Field><Submit>生成紫微命盘</Submit></form>{seed!==null&&<section className="tool-result"><ResultTitle kicker="紫微斗数 · 十二宫" title="星曜宫位全盘" note="点击宫位可结合现实经历自行核对"/><div className="palace-grid">{palaces.map((p,i)=><article key={p} className={i===0?"major":""}><span>{branches[(i+seed)%12]}宫</span><h3>{p}</h3><b>{stars[seeded(seed,i,stars.length)]}</b><small>{stars[seeded(seed,i+20,stars.length)]} · {elements[seeded(seed,i+40,5)]}</small></article>)}</div><InsightCards items={[["命宫主轴","重视秩序与长期积累，越能自主安排节奏，越容易发挥稳定优势。"],["官禄方向","适合需要研究、规划、表达与系统建设的角色。"],["福德提醒","思虑多时应主动切换到身体活动，让精神从循环中退出。"]]}/></section>}</>}

function Meihua(){const [result,setResult]=useState<{upper:number;lower:number;moving:number;question:string}|null>(null);function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),a=+String(f.get("a")),b=+String(f.get("b"));setResult({upper:a%8,lower:b%8,moving:(a+b)%6+1,question:String(f.get("q"))})}return <><form className="tool-card" onSubmit={go}><div className="tool-title"><b>梅花心易</b><span>一念一问，报出最先出现的两个数字</span></div><Field label="具体问题"><textarea name="q" required placeholder="例如：这个合作本周能否顺利推进？"/></Field><div className="form-grid"><Field label="第一个数字"><input name="a" required type="number" min="1" defaultValue="7"/></Field><Field label="第二个数字"><input name="b" required type="number" min="1" defaultValue="23"/></Field></div><Submit>生成梅花卦</Submit></form>{result&&<section className="tool-result"><ResultTitle kicker={`所问：${result.question}`} title={`${trigramNames[result.upper]}上${trigramNames[result.lower]}下`} note={`第 ${result.moving} 爻动 · 体用关系观察`}/><div className="meihua-symbols"><div><strong>{trigramSymbols[result.upper]}</strong><span>上卦 · {trigramNames[result.upper]}</span></div><i>☯</i><div><strong>{trigramSymbols[result.lower]}</strong><span>下卦 · {trigramNames[result.lower]}</span></div></div><InsightCards items={[["当下之象","事情已有基础，但外部节奏仍在调整；不宜用一次回应判断全部走向。"],["体用关系","先守住核心目标，再根据对方反馈调整形式，不要同时改变目标与方法。"],["决策建议","设置一个明确的观察节点，在此之前推进最小可验证步骤。"]]}/></section>}</>}

function Liuyao(){const [mode,setMode]=useState("manual"),[q,setQ]=useState(""),[lines,setLines]=useState<Line[]>(Array.from({length:6},()=>({yang:true,moving:false}))),[done,setDone]=useState(false);function cycle(i:number){setLines(x=>x.map((l,j)=>j!==i?l:l.yang&&!l.moving?{yang:false,moving:false}:!l.yang&&!l.moving?{yang:true,moving:true}:l.yang?{yang:false,moving:true}:{yang:true,moving:false}))}function submit(e:FormEvent){e.preventDefault();if(mode==="random")setLines(Array.from({length:6},()=>({yang:Math.random()>.5,moving:Math.random()>.7})));setDone(true)}const moving=lines.filter(l=>l.moving).length;return <><form className="tool-card" onSubmit={submit}><Field label="占问问题"><textarea required value={q} onChange={e=>setQ(e.target.value)} placeholder="一事一卦，例如：是否应该接受这份工作？"/></Field><div className="mini-tabs">{[["manual","铜钱录入"],["time","时间起卦"],["number","数字起卦"],["random","随机起卦"]].map(x=><button type="button" className={mode===x[0]?"active":""} key={x[0]} onClick={()=>setMode(x[0])}>{x[1]}</button>)}</div><div className="liuyao-editor">{[5,4,3,2,1,0].map(i=><button type="button" key={i} onClick={()=>cycle(i)}><span>{["初爻","二爻","三爻","四爻","五爻","上爻"][i]}</span><Line line={lines[i]}/><small>{lines[i].moving?"动爻":lines[i].yang?"少阳":"少阴"}</small></button>)}</div><Submit>生成完整六爻盘</Submit></form>{done&&<section className="tool-result dark-result"><ResultTitle kicker={`所问：${q}`} title={moving?"乾之变卦":"乾为天 · 静卦"} note={`${moving} 个动爻 · 世应纳甲排盘`}/><div className="yao-chart">{[5,4,3,2,1,0].map((i,row)=><div key={i}><span>{["青龙","朱雀","勾陈","螣蛇","白虎","玄武"][row]}</span><Line line={lines[i]}/><b>{["父母戌土","官鬼申金","妻财午火","子孙辰土","兄弟寅木","父母子水"][row]}</b><i>{i===4?"世":i===1?"应":"—"}</i><small>{lines[i].moving?"发动":"安静"}</small></div>)}</div><InsightCards items={[["局势","先看动爻落在哪个现实环节，变化越集中，越适合小步试验。"],["世应","把自己的期待和对方的真实条件分开确认，避免用想象填补信息。"],["行动","设置可撤回的下一步，并约定明确的复盘时间。"]]}/></section>}</>}

function Tarot(){const deck=["愚者","魔术师","女祭司","皇后","皇帝","恋人","战车","力量","隐者","命运之轮","正义","星星","太阳","世界"],descs=["允许新的可能进入，但先确认你愿意承担什么。","资源已经在手，关键是聚焦并开始行动。","答案尚未完全显现，安静观察比追问更有效。","滋养正在发生，给计划更多时间与空间。","建立结构、规则和边界，混乱会因此减少。","价值选择比表面得失更重要。","明确方向后持续推进，不必回应所有杂音。","柔韧的坚定比强行控制更有力量。","暂时后退一步，独立思考会带来清晰。","周期正在转换，保留弹性。","面对事实，并承担选择带来的对应结果。","希望不是等待，而是持续校准方向。","事情趋向明朗，适合坦诚表达。","一个阶段可以完成，也意味着新的循环。"], [cards,setCards]=useState<number[]>([]);function draw(){const s=Date.now();setCards([0,1,2].map(i=>seeded(s,i,deck.length)).filter((x,i,a)=>a.indexOf(x)===i));}return <><section className="tool-card tarot-table"><div className="tool-title"><b>三张牌阵</b><span>过去 · 当下 · 建议</span></div><div className="tarot-deck"><div className="card-back">知<small>命</small></div><p>闭上眼睛想清楚问题，准备好后抽取三张牌。</p><button type="button" className="tool-submit" onClick={draw}>洗牌并抽牌 <span>✦</span></button></div></section>{cards.length>0&&<section className="tool-result"><ResultTitle kicker="三张牌已翻开" title="看见故事，而不是判决" note="从左到右：过去、当下、行动建议"/><div className="tarot-cards">{cards.map((c,i)=><article key={i}><div><span>{String(c+1).padStart(2,"0")}</span><b>{["☾","✦","☉"][i]}</b><small>知命</small></div><p>{["过去","当下","建议"][i]}</p><h3>{deck[c]}</h3><span>{descs[c]}</span></article>)}</div></section>}</>}

function Huangli(){const [date,setDate]=useState(new Date().toISOString().slice(0,10));const seed=hash(date),good=["签约","会友","整理","学习","出行","开工","纳财","安床"],bad=["冲动决策","争辩","熬夜","远行","动土","大额消费"];return <><section className="tool-card calendar-tool"><Field label="选择日期"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><div className="calendar-date"><strong>{new Date(`${date}T12:00`).getDate()}</strong><div><b>{new Date(`${date}T12:00`).toLocaleDateString("zh-CN",{year:"numeric",month:"long",weekday:"long"})}</b><span>{stems[seed%10]}{branches[seed%12]}日 · {elements[seed%5]}气当令</span></div></div></section><section className="tool-result"><ResultTitle kicker="今日黄历" title={seed%3===0?"先定后动，稳中求进":"顺势而为，留有余地"} note={`冲${branches[(seed+6)%12]} · 煞${["东","南","西","北"][seed%4]}`}/><div className="yi-ji"><div><b>宜</b>{[0,1,2,3].map(i=><span key={i}>{good[seeded(seed,i,good.length)]}</span>)}</div><div><b>忌</b>{[0,1,2].map(i=><span key={i}>{bad[seeded(seed,i+9,bad.length)]}</span>)}</div></div><div className="hours"><h3>十二时辰</h3>{branches.map((b,i)=><div key={b} className={seeded(seed,i,3)>0?"good":"bad"}><b>{b}时</b><span>{String(i*2).padStart(2,"0")}:00</span><small>{seeded(seed,i,3)>0?"吉":"平"}</small></div>)}</div><InsightCards items={[["今日节奏","上午适合推进清晰任务，下午保留缓冲，晚间以复盘为主。"],["行动提醒","黄历是择时参考，不应替代天气、交通、合同与专业风险判断。"],["幸运线索",`方位宜${["东","南","西","北"][seeded(seed,20,4)]}，可用${["青绿","暖金","米白","朱红"][seeded(seed,21,4)]}色作为今日提醒。`]]}/></section></>}

function Line({line}:{line:Line}){return <span className={`line-mark ${line.yang?"yang":"yin"} ${line.moving?"moving":""}`}><i/><i/>{line.moving&&<b>{line.yang?"○":"×"}</b>}</span>}
function ResultTitle({kicker,title,note}:{kicker:string;title:string;note:string}){return <div className="result-title"><p className="eyebrow">{kicker}</p><h2>{title}</h2><span>{note}</span></div>}
function ElementBars({values}:{values:number[]}){return <div className="element-bars">{elements.map((e,i)=><label key={e}><b>{e}</b><i><span style={{width:`${values[i]}%`}}/></i><em>{values[i]}%</em></label>)}</div>}
function InsightCards({items}:{items:string[][]}){return <div className="analysis-grid">{items.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div>}
